export const key_attributes = {
    'AM (C)': ['Passing', 'Vision', 'Decisions', 'Teamwork', 'Technique', 'Off The Ball'],
    'AM (L)': ['Dribbling', 'Crossing', 'Technique', 'Off The Ball', 'Pace'],
    'AM (LC)': ['Dribbling', 'Passing', 'Vision', 'Decisions', 'Teamwork', 'Technique', 'Off The Ball'],
    'AM (R)': ['Dribbling', 'Crossing', 'Technique', 'Off The Ball', 'Pace'],
    'AM (RC)': ['Dribbling', 'Passing', 'Vision', 'Decisions', 'Teamwork', 'Technique', 'Off The Ball'],
    'AM (RL)': ['Dribbling', 'Crossing', 'Technique', 'Off The Ball', 'Pace'],
    'AM (RLC)': ['Dribbling', 'Passing', 'Vision', 'Decisions', 'Teamwork', 'Technique', 'Off The Ball'],
    'D (C)': ['Jumping Reach', 'Tackling', 'Decisions', 'Positioning', 'Strength', 'Aggression', 'Teamwork'],
    'D (L)': ['Dribbling', 'Tackling', 'Stamina', 'Jumping Reach', 'Passing', 'Decisions', 'Off The Ball', 'Positioning'],
    'D (LC)': ['Dribbling', 'Tackling', 'Stamina', 'Jumping Reach', 'Passing', 'Decisions', 'Off The Ball', 'Positioning', 'Strength', 'Aggression', 'Teamwork'],
    'D (R)': ['Dribbling', 'Tackling', 'Stamina', 'Jumping Reach', 'Passing', 'Decisions', 'Off The Ball', 'Positioning'],
    'D (RC)': ['Dribbling', 'Tackling', 'Stamina', 'Jumping Reach', 'Passing', 'Decisions', 'Off The Ball', 'Positioning', 'Strength', 'Aggression', 'Teamwork'],
    'D (RL)': ['Dribbling', 'Tackling', 'Stamina', 'Jumping Reach', 'Passing', 'Decisions', 'Off The Ball', 'Positioning'],
    'D (RLC)': ['Dribbling', 'Tackling', 'Stamina', 'Jumping Reach', 'Passing', 'Decisions', 'Off The Ball', 'Positioning', 'Strength', 'Aggression', 'Teamwork'],
    'D/AM (R)': ['Dribbling', 'Crossing', 'Technique', 'Off The Ball', 'Pace', 'Dribbling', 'Tackling', 'Stamina', 'Jumping Reach', 'Passing', 'Decisions', 'Off The Ball', 'Positioning'],
    'D/M (C)': ['Passing', 'Decisions', 'Teamwork', 'Tackling', 'Technique', 'Vision', 'Positioning'],
    'D/M (L)': ['Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Crossing', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/M (R)': ['Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Crossing', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/M (RL)': ['Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Crossing', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/M/AM (L)': ['Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Crossing', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/M/AM (R)': ['Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Crossing', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/M/AM (RL)': ['Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Crossing', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/WB (L)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/WB (R)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/WB (RL)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/WB/AM (L)': ['Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Crossing', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/WB/AM (R)': ['Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Crossing', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/WB/M (L)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning'],
    'D/WB/M (R)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning'],
    'D/WB/M (RL)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning'],
    'D/WB/M/AM (L)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/WB/M/AM (R)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'D/WB/M/AM (RL)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'DM': ['Tackling', 'Aggression', 'Strength', 'Dribbling', 'Decisions', 'Positioning', 'Teamwork', 'Stamina'],
    'GK': ['Aerial Reach', 'Agility', 'Handling', 'Reflexes'],
    'M (C)': ['Passing', 'Decisions', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning'],
    'M (L)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning'],
    'M (LC)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning', 'Decisions'],
    'M (R)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning'],
    'M (RC)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning', 'Decisions'],
    'M (RL)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning'],
    'M (RLC)': ['Dribbling', 'Passing', 'Teamwork', 'Technique', 'Off The Ball', 'Positioning', 'Decisions'],
    'M/AM (C)': ['Passing', 'Vision', 'Decisions', 'Teamwork', 'Technique', 'Off The Ball'],
    'M/AM (L)': ['Dribbling', 'Crossing','Technique', 'Off The Ball', 'Pace'],
    'M/AM (LC)': ['Passing', 'Vision', 'Decisions', 'Teamwork', 'Pace', 'Technique', 'Off The Ball', 'Dribbling', 'Crossing'],
    'M/AM (R)': ['Dribbling', 'Crossing','Technique', 'Off The Ball', 'Pace'],
    'M/AM (RC)': ['Passing', 'Vision', 'Decisions', 'Teamwork', 'Pace', 'Technique', 'Off The Ball', 'Dribbling', 'Crossing'],
    'M/AM (RL)': ['Dribbling', 'Crossing','Technique', 'Off The Ball', 'Pace'],
    'M/AM (RLC)': ['Passing', 'Vision', 'Decisions', 'Teamwork', 'Pace', 'Technique', 'Off The Ball', 'Dribbling', 'Crossing'],
    'ST (C)': ['Finishing', 'Decisions', 'Off The Ball', 'Dribbling', 'Jumping Reach', 'Technique', 'Teamwork', 'Pace', 'Strength'],
    'WB (L)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB (R)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB (RL)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/AM (L)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/AM (R)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/AM (RL)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/M (L)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/M (R)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/M (RL)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/M/AM (L)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/M/AM (R)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace'],
    'WB/M/AM (RL)': ['Crossing', 'Dribbling', 'Tackling', 'Decisions', 'Stamina', 'Technique', 'Off The Ball', 'Positioning', 'Teamwork', 'Pace']
}